### PR TITLE
Navbar and Header Updates (Laptop/Desktop)

### LINKED ISSUE #39: "What We Do" Hero Section
Gradient background block, header and caption and geometric pattern. 

Nav labels and button on gradient background are white.

### PR DESCRIPTION
**Pull request by sreya-kata**
Did the following:
- Made the navbar and gradient header according to the hifi design
- Navbar style differs from homepage and all other pages
- Geometric image on header only on "what we do" and "what's happening" and disappears after a max width
- Made a separate issue for navbar mobile version/hamburger

Home navbar:
home

What we do navbar + header:
whatwe-do

What's happening navbar + header in a reduced width viewport:
what's-happening

### CODE REVIEW

**Comment by josephmannis** [comment]
Can you take a look at the failing checks please?

**Comment by sreya-kata** [comment]
My bad! Forgot I changed something in the CMS

**Review by josephmannis — CHANGES_REQUESTED** [review]
Overall looks good – the image for the background is pretty low res though. Can you please use an SVG instead? Also, that Safari bug with font sizing is still present. Let me know if you need help there.

Can you also send along the preview link to Riha and get design approval? Thanks!

**Comment by sreya-kata** [comment]
Updates:
- changed header to svg
- fixed safari font bug by making min-height: 0vw (see [stackoverflow](https://stackoverflow.com/questions/37070694/font-size-calc-dynamic-size-safari-failing) and [alleyway fix](https://github.com/Scout-NU/thealleyway-site/pull/74))
- got design team approval

**Review by josephmannis — APPROVED** [review]
🙆🏼

**Pull request merged**
